name: FurrSecurity
version: '${version}'
main: org.grinch.furrsecurity.paper.FurrSecurityPaper
api-version: '1.21'
description: Verificacion de identidad del staff con Discord
author: GrinchHorizon
website: https://tebby.lgbt

commands:
  furrsecurity:
    description: Administracion de FurrSecurity
    usage: /<command> [reload|status|check|reset|help]
    aliases: [fsec, fs]
    permission: furrsecurity.admin

permissions:
  furrsecurity.admin:
    description: Usar /furrsecurity
    default: op
  furrsecurity.staff:
    description: Marca al jugador como staff que debe verificar su identidad
    default: false
  furrsecurity.notify:
    description: Recibe avisos de verificaciones pendientes
    default: op
